spring:
  application:
    name: service-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
  logging:
    file:
      name: Logs.log

    level:
      root: INFO